[general]

import = [
  "~/.config/alacritty/themes/rose_pine_dawn.toml",
  # "~/.config/alacritty/themes/github_light.toml",

  # "~/.config/alacritty/themes/catppuccin_mocha.toml",
  # "~/.config/alacritty/themes/rose_pine.toml",
  # "~/.config/alacritty/themes/oxocarbon.toml",
  # "~/.config/alacritty/themes/nord.toml",
  # "~/.config/alacritty/themes/dracula.toml",
  # "~/.config/alacritty/themes/rose_pine.toml",
]

[env]

TERM = "xterm-256color"

[window]

opacity = 0.95

padding.x = 5
padding.y = 5

decorations = "Full"

startup_mode = "Maximized"

option_as_alt = "OnlyLeft"

[terminal]

shell = { program = "/bin/zsh", args = [] }

[font]

normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
