[general]

import = ["~/.config/alacritty/themes/catppuccin-latte.toml"]

[window]

opacity = 0.9

padding.x = 5
padding.y = 5

decorations = "Full"

startup_mode = "Maximized"

[terminal]

[terminal.shell]
program = "/bin/zsh"
