[window]

opacity = 0.9

padding.x = 5
padding.y = 5

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

startup_mode = "Maximized"

[terminal]

[terminal.shell]
program = "/bin/bash"
