[general]

import = [
  "~/.config/alacritty/themes/themes/rose_pine_dawn.toml",
  # "~/.config/alacritty/themes/themes/github_light.toml",

  # "~/.config/alacritty/themes/themes/catppuccin_mocha.toml",
  # "~/.config/alacritty/themes/themes/rose_pine.toml",
  # "~/.config/alacritty/themes/themes/oxocarbon.toml",
  # "~/.config/alacritty/themes/themes/nord.toml",
  # "~/.config/alacritty/themes/themes/dracula.toml",
]

[env]

TERM = "xterm-256color"

[window]

opacity = 0.95

padding.x = 5
padding.y = 5

decorations = "Full"

startup_mode = "Maximized"

[terminal]

shell = { program = "/bin/zsh", args = [] }

[font]

normal = { family = "MesloLGS NF" }
