site_name: dotfiles
site_url: https://hieudao-code.github.io/dotfiles
repo_url: https://github.com/HieuDao-code/dotfiles
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - content.code.copy
    - content.tooltips
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
  - README.md
  - Tools:
      - alacritty.md
      - zsh.md
      - tmux.md
      - window_manager.md
      - neovim.md
      - python.md
  - key_binding.md
